### PR TITLE
Refactored Inputs, config.schema.json, and updated eiscp fork

### PR DESCRIPTION
**Pull request by solowalker27**
Before submitting your PR, please review the following checklist:

- [x] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement use `master` branch
- [x] **TEST**: run "npm test" before commiting
- [x] **TEST MORE**: run "npm install" to check if you dependencies are OK
- [x] **LIST ISSUES** this PR resolves
Directly addresses:
https://github.com/solowalker27/homebridge-onkyo/issues/13
https://github.com/ToddGreenfield/homebridge-onkyo/issues/70
https://github.com/ToddGreenfield/homebridge-onkyo/issues/75
https://github.com/ToddGreenfield/homebridge-onkyo/issues/79
https://github.com/ToddGreenfield/homebridge-onkyo/issues/77

Touches code around and thus potentially addresses (this should at least be looked at again after this):
https://github.com/ToddGreenfield/homebridge-onkyo/issues/74
https://github.com/ToddGreenfield/homebridge-onkyo/issues/72
https://github.com/ToddGreenfield/homebridge-onkyo/issues/71
https://github.com/ToddGreenfield/homebridge-onkyo/issues/68
https://github.com/ToddGreenfield/homebridge-onkyo/issues/63
- [ ] **KEEP PR small** so it could be easily reviewed.
- [x] **AVOID** making unnecessary stylistic changes in unrelated code

Manually merged my changes back in. Ran `npm test` and fixed all the linting errors. Performed a sanity check with my own Onkyo and confirmed it's functioning properly. I tried to keep your styling changes as much as possible. I updated the input mapping to use your `input_name` and `display_name`. Did some cleanup along the way. Should hopefully be easier to review and more immediately testable.

### CODE REVIEW

**Review by bradhs — APPROVED** [review]
Can we get this committed so we can use tv for invput?

**Comment by cbrandlehner** [comment]
Sorry guys, I was really busy caused by a covid-19 project that forced me to work literally every day since April this year.
I lost track of all the changes, so please give me some short update what kind of help is needed here.

To give you some background info: I am authorized to merge commits on GitHub. To publish a new release on npmjs.org we need help from @ToddGreenfield 

@ToddGreenfield to make things easier: in another project I added an npm token to my GitHub repository and enabled a GitHub action to push a new release to npm every time a new release was published on GitHub.
This is the action: https://github.com/cbrandlehner/homebridge-daikin-local/blob/master/.github/workflows/npmpublish.yml
Token documentation: https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages

**Comment by ToddGreenfield** [comment]
@cbrandlehner You should be authorized to publish on npm for this package. Sorry guys, I just don't have time to maintain or assist.

**Comment by cbrandlehner** [comment]
@ToddGreenfield good to know, thanks. ALL, if you need me to publish something, please let me know.

**Comment by xkampotx** [comment]
hey there, any news regarding merging this PR? :)

**Comment by cbrandlehner** [comment]
If this is what is needed, I can easily help.

**Comment by johnlietzke** [comment]
I would definitely use the DRX receiver support.  Anything I can do to help please let me know.

**Comment by jondthompson** [comment]
So is this the main repo now with 0.7.x, or is @ToddGreenfield's with 0.8.0?

**Comment by Jacksonbm1** [comment]
I'm curious if anyone figured this out

**Comment by johnlietzke** [comment]
Yes. It works. Just lots of trial and error. For the DRX 4 use the name DRX-4 input is bd.

**Pull request merged**
