### PR TITLE
Fix for https://github.com/ToddGreenfield/homebridge-onkyo/issues/82, ignore case for zone variable.

### PR DESCRIPTION
**Pull request by jondthompson**
Most of the change is outlined in the issue this resolves by creating a dictionary for the eiscp connection, then reusing it for zones that have the same IP address. 

The only other thing I did in here is line 71, which changes the zone variable to all lowercase, eliminating the possibility that it can be wrong due to case issues.

### CODE REVIEW

**Comment by cbrandlehner** [comment]
Unfortunately the code change does not pass quality check.

"npm test" failed.

**Comment by cbrandlehner** [comment]
The problem was easy to fix (missing semicolon, etc).
I commited a fixed version.

**Comment by jondthompson** [comment]
Thanks

Jon Thompson
Evolve
515 360 1351
www.dmevolve.com

**Comment by cbrandlehner** [comment]
Jon, can you please have a look at issue #110

**Pull request merged**
