### PR TITLE
Convert from Switch to new TV accessory in iOS 12.2

### PR DESCRIPTION
**Pull request by solowalker27**

### CODE REVIEW

**Comment by solowalker27** [comment]
This will require iOS 12.2. As such, it probably shouldn't be merged until 12.2 is released.

**Comment by solowalker27** [comment]
Some discussion on these changes occurred in #19 beginning with https://github.com/ToddGreenfield/homebridge-onkyo/issues/19#issuecomment-462225897

**Comment by solowalker27** [comment]
I've made significant changes to this PR:

- Plugin is now a Platform.
- Support an optional Dimmer switch for separate volume control.
- Restore legacy Switch service for those who haven't upgraded to iOS 12.2 yet.

With these changes, I'd feel comfortable recommending merging this before iOS 12.2's public release.

**Comment by ToddGreenfield** [comment]
created a new devel branch for testing-

**Comment by ToddGreenfield** [comment]
I am unable to use the legacy switch via the PR. "Error: The requested accessory 'Onkyo-tv' was not registered by any plugin."

**Comment by solowalker27** [comment]
Yeah, you still have to convert it to a platform and not accessory in your config. But with the `“switch_service”` flag in the config it will add it as a switch instead of tv. I updated the ReadMe with an example.

**Comment by ToddGreenfield** [comment]
Sorry, doing too many things at once- Yes, I converted to a platform and was able to restart without error, however no switch (re)appeared.

**Comment by solowalker27** [comment]
And you set `”switch_service”: true`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by solowalker27** [comment]
Something like this, using the example, should work. Note that `”switch_service”` is `true`.
```platforms": [{
+        "platform": "Onkyo",
+        "name": "Onkyo",
+        "receivers": [
+            {
+                "model": "TX-NR609",
+                "ip_address": "10.0.1.6",
+                "poll_status_interval": "3000",
+                "max_volume": "55",
+                "map_volume_100": true,
+                "name": "Receiver",
+                "inputs": {
+                    "dvd": "Blu-ray",
+                    "video2": "Switch",
+                    "video3": "Xbox",
+                    "video6": "Apple TV",
+                    "video4": "AUX",
+                    "cd": "TV/CD"
+                },
+                "volume_dimmer": false,
+			        "switch_service": true
+            }
+        ]
+    }]```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ToddGreenfield** [comment]
Yes. I left the dimmer to false though-

**Comment by solowalker27** [comment]
I’ve tested it and it worked for me. Maybe try deleting your `homebridge/accessories/` directory and restart homebridge.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ToddGreenfield** [comment]
Removed both accessories and persist, restarted… same thing, doesn’t show up.
Config-


"platforms":[
        {
       "platform": "Onkyo",
       "name": "Onkyo",
       "receivers": [
           {
               "model": "TX-NR609",
               "ip_address": "192.168.1.108",
               "poll_status_interval": "3000",
               "default_input": "net",
               "default_volume": "10",
               "max_volume": "40",
               "map_volume_100": true,
               "name": "Stereo",
               "inputs": {
                   "net": "Network",
                   "video2": "Switch",
                   "video3": "Xbox",
                   "video6": "Apple TV",
                   "video4": "AUX",
                   "cd": "TV/CD"
               },
               "volume_dimmer": false,
               "switch_service": true
           }
       ],

**Comment by ToddGreenfield** [comment]
I fixed it. Something was wrong with my config.json but homebridge was not throwing an error on startup. Works now-

**Comment by solowalker27** [comment]
Glad to hear it. I was just trying to debug again and I couldn't figure out what might be wrong; it even was working fine on my wife's iPhone on iOS 12.1 and my Mac on 10.14.3.

But, digging in I did notice that I accidentally left the logging pretty noisy. If that bothers you or anyone else I'm happy to turn it down, to change so `info` to `debug`.

**Comment by toshibochan** [comment]
I have this in my config file but input not showing on home app.

        "accessories": [{
                "accessory": "Onkyo-tv",
                "name": "Onkyo",
                "model": "TX-NR609",
                "ip_address": "10.0.1.14",
                "poll_status_interval": "900",
                "default_input": "cbl",
                "max_volume": "100",
                "map_volume_100": true,
                "zone": "zone2",
                "inputs": {
                        "bd": "APTV 4K",
                        "cbl": "APTV JP",
                        "pc": "FireTV"

**Comment by toshibochan** [comment]
I try platform to but in the input selection on the app is empty.

{
	"bridge": {
		"name": "Homebridge Pi3BPlus",
		"username": "CC:22:3D:A3:AE:FA",
		"port": 51826,
		"pin": "031-45-155"
	},

	"platforms": [{
		"platform": "Onkyo",
		"name": "Onkyo",
		"receivers": [{
			"model": "TX-NR609",
			"ip_address": "10.0.1.6",
			"poll_status_interval": "3000",
			"max_volume": "55",
			"map_volume_100": true,
			"name": "Receiver",
			"inputs": {
				"dvd": "Blu-ray",
				"video2": "Switch",
				"video3": "Xbox",
				"video6": "Apple TV",
				"video4": "AUX",
				"cd": "TV/CD"
			},
			"volume_dimmer": false,
			"switch_service": false
		}]
	}]
}

**Comment by toshibochan** [comment]
hi @ToddGreenfield I see your comment "I do not have 12.2 yet but created a new devel branch for others to test-". where is this devel branch for testing?

**Comment by solowalker27** [comment]
@toshibochan my first guess is your input list would be empty because the input map you provided doesn’t use the expected names for the inputs, I’d imagine. Try it without the input map on your config first and see if it works and the default inputs are populated.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toshibochan** [comment]
I was able to do with this config. 
but now how to add zone2 and zone3 ? I try to add ("zone" : "zone2"), after  ("name": "Receiver"), but didn't work.


        "platforms": [{
                "platform": "Onkyo",
                "name": "Onkyo",
                "receivers": [{
                        "model": "TX-NR609",
                        "ip_address": "10.0.1.14",
                        "poll_status_interval": "3000",
                        "max_volume": "100",
                        "map_volume_100": true,
                        "name": "Receiver",
                        "inputs": {
                                "dvd": "APTV 4K",
                                "video2": "APTV JP",
                                "video6": "FireTV"
                        },
                        "volume_dimmer": true,
                        "switch_service": false
                }]
        }]
}

**Comment by toshibochan** [comment]
I tried the but didn't work.

{
	"bridge": {
		"name": "Homebridge Pi3BPlus",
		"username": "CC:22:3D:A2:AE:FB",
		"port": 51826,
		"pin": "031-45-155"
	},

	"platforms": [{
		"platform": "Onkyo",
		"name": "Onkyo",
		"receivers": [{
			"model": "TX-NR609",
			"ip_address": "10.0.1.14",
			"poll_status_interval": "3000",
			"max_volume": "100",
			"map_volume_100": true,
			"name": "Receiver",
			"inputs": {
				"dvd": "APTV 4K",
				"video2": "APTV JP",
				"video6": "FireTV"
			},
			"volume_dimmer": true,
			"switch_service": false
		}, {
			"platform": "Onkyo",
			"name": "Onkyo",
			"receivers": [{
				"model": "TX-NR609",
				"ip_address": "10.0.1.14",
				"poll_status_interval": "3000",
				"max_volume": "100",
				"map_volume_100": true,
				"name": "Receiver zone2",
   				"zone" : "zone2",
				"inputs": {
					"dvd": "APTV 4K",
					"video2": "APTV JP",
					"video6": "FireTV"
				},
				"volume_dimmer": true,
				"switch_service": false
			}]
		}]
	}]
}

**Comment by toshibochan** [comment]
I try run second Homebridge doing (homebridge -U ~/.homebridge2) and I was able to control zone2 but main zone lose connection. and if I restart main zone homebridge zone 2 lose connection. is the any way to use main zone and zone2 same time?

**Comment by ToddGreenfield** [comment]
Unfortunately only one zone is supported at a time. So EITHER zone1 OR zone2 OR zone3... not all of them simultaneously will work. I am thinking only one active connection at a time is the problem. I personally don’t use multiple zones.

The devel branch is selected up at the top of github where it says master.

**Pull request merged**
